version: "3.3"
services:

  app:
    build:
      context: ./
    ports:
      - "8080:8080"
    networks:
      - internal
    container_name: app-v9

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
    networks:
      - internal
    depends_on:
      - app

    container_name: elasticsearch-v9

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.2
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      ELASTIC_HOSTS: "elasticsearch:9200"
      MONITORING_ENABLED: "false"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - internal
    depends_on:
      - elasticsearch
    container_name: logstash-v9

  filebeat:
    build:
      context: ./filebeat
      args:
        ELASTIC_STACK_VERSION: 7.15.2
    ports:
      - "5066:5066"
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro       # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/lib/docker/containers:/usr/share/dockerlogs/data:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
      - ./filebeat/data:/usr/share/filebeat/data:rw                        # Persistence data


    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure
    networks:
      - internal
    depends_on:
      - logstash
    container_name: filebeat-v9

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      MONITORING_KIBANA_COLLECTION_ENABLED: "false"
    ports:
      - "5601:5601"
    networks:
      - internal
    depends_on:
      - logstash
    container_name: kibana-v9
networks:
  internal:

volumes:
  elasticsearch:
